name: farmwise-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - google-generativeai=0.8.2
  - python-dotenv=1.0.1
  - requests=2.31.0
  - pip
  - markdown # Added markdown dependency
  - pip:
      - gunicorn=22.0.0